config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :goals

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  patch 'goals/:id/' => 'goals#move_up', as: :move_goal_up

  root "users#index"

end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :authorize

  def index
  end

  def new
  end

  def create
    @goal_new = Goal.new goal_params
    @goal_new.user = current_user 
    @goal_new.ranking = Goal.where(user_id: current_user.id).count + 1
    if @goal_new.save
      redirect_to '/users/show', notice: "goal created :)"
    else
      redirect_to '/users/show', alert: "goal not created..."
    end
  end

  def show
  end

  def edit
    redirect_to '/users/show', alert: "access denied" unless can? :update, @goal
    if @goal.update goal_params
      redirect_to @goal, notice: "Goal updated successfully!"
    else
      redirect_to '/users/show'
    end
  end

  def update
  end

  def destroy
    find_goal
    @goal.destroy
    redirect_to '/users/show', notice: "goal removed"
    rank_goals
  end

  def move_up
    render params
    # find_goal
    # @goal_above = Goal.where(ranking: (@goal.ranking - 1))
    # @goal.ranking = @goal.ranking - 1
    # @goal_above.ranking = @goal_above.ranking + 1
    # @goal.save
    # @goal_above.save
    # redirect_to '/users/show'
  end

  private

  def goal_params
    params.require(:goal).permit([:ranking, :description])
  end

  def find_goal
    @goal = Goal.find(params[:id])
  end

  def rank_goals
    @goal_user = Goal.where(user_id: current_user.id).order(:ranking)
    counter = 0
    @goal_user.each do |goal|
      counter += 1
      goal.ranking = counter
      goal.save
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
    @user = User.new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def show
    @goal = Goal.where(user_id: current_user.id).order(:ranking)
    @new_goal = Goal.new
  end

  def edit
  end

  def update
    find_user
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    find_user
    if @user.destroy
      redirect_to user_path
    else
      render :index
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/ccreate.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/ccreate.html.erb</p>

app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/ccreate.html.erb</p>

app/views/goals/destroy.html.erb
<h1>Goals#destroy</h1>
<p>Find me in app/views/goals/destroy.html.erb</p>

app/views/goals/edit.html.erb
<h1>Goals#edit</h1>
<p>Find me in app/views/goals/edit.html.erb</p>

app/views/goals/index.html.erb
<h1>Goals#index</h1>
<p>Find me in app/views/goals/index.html.erb</p>

app/views/goals/new.html.erb
<h1>Goals#new</h1>
<p>Find me in app/views/goals/new.html.erb</p>

app/views/goals/show.html.erb
<h1>Goals#show</h1>
<p>Find me in app/views/goals/show.html.erb</p>

app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BetterHuman</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<% if current_user %>
	  Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
	<% else %>
	  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
	<% end %>

	<% if flash[:notice] %>
  		<div class="alert alert-success"><%= flash[:notice] %></div>
	<% elsif flash[:alert] %>
  		<div class="alert alert-danger"><%= flash[:alert] %></div>
	<% end %>
	
<%= yield %>

</body>

</html>

app/views/users/ccreate.html.erb
<h1>Users#ccreate</h1>
<p>Find me in app/views/users/ccreate.html.erb</p>

app/views/users/create.html.erb
<h1>Users#ccreate</h1>
<p>Find me in app/views/users/ccreate.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<p> testing</p>

<% @user.each do |user| %>
		<%= user.name %>
		<%= user.email %>
		<br>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<% @goal.each do |goal| %>
	<table>
		<tr>
			<td><%= link_to "move up", move_goal_up_path(goal), method: :patch, class: "btn btn-default", remote: true %></td>
			<td><%= goal.ranking %></td>
			<td><%= goal.description %></td>
			<td>edit</td>
			<td>
				<%= link_to "delete", goal, method: :delete, class: "btn btn-default" %>
			</td>
		</tr>
		<br>
	</table>
<% end %>
	<table>
		<tr><br></tr>
		<tr>
			<td>
			<%=  form_for @new_goal do |new_goal| %>
				<%= new_goal.text_area :description, :value => "my next goal" %>
			</td>
			<td>
				<%= new_goal.submit 'add goal' %>
			</td>
		<% end %>
		</tr>
</table>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>